CREATE DATABASE IF NOT EXISTS NIET;

USE NIET;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

INSERT INTO users (email, password)
VALUES ('student@n123.com', 'password123')
ON DUPLICATE KEY UPDATE password = VALUES(password);
